### ISSUE TITLE
incorrect arguments to scePsmDrmGetRifKey

### ISSUE THREAD

**Issue by LiEnby** [EliCrystal2001/CrystalArchiver#3]
the correct signature for the function is `int scePsmDrmGetRifKey(const ScePsmDrmLicense *license_buf, char *keydata, int* flags, uint64_t* expire_date, uint64_t* end_date);` it is basically pure luck that this tool works at all.

**Comment by EliCrystal2001** [comment]
you mean uint64_t[2}? that's what you put in at https://github.com/vitasdk/vita-headers/pull/836

**Comment by LiEnby** [comment]
oh that wasn't right either so.

**Comment by EliCrystal2001** [comment]
thanks.
